apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kurtosis

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: kurtosis
      app.kubernetes.io/component: engine
      app.kubernetes.io/managed-by: kustomize
